### ISSUE TITLE
Cannot depend on mbd.TaxaAndMbness due to long paths

### ISSUE THREAD

**Issue by richelbilderbeek** [Giappo/mbd.TaxaAndMbness#1]
Hi Giovanni,

In [this Travis log](https://travis-ci.org/richelbilderbeek/razzo/builds/596929154#L1400) I see `razzo` cannot depend on mbd.TaxaAndMbness due to long paths.

I remove `razzo` depending on `mbd.TaxaAndMbness` until this is fixed. I'll find a quick-and-dirty workaround until then :+1:

**Comment by Giappo** [comment]
@richelbilderbeek it should be ok now. Please check

**Comment by richelbilderbeek** [comment]
Thanks! Will do :+1:

(added Issue [https://github.com/richelbilderbeek/razzo/issues/349](https://github.com/richelbilderbeek/razzo/issues/349))

**Comment by richelbilderbeek** [comment]
Error still occurs: [see Travis log](https://travis-ci.org/richelbilderbeek/razzo/builds/598166754#L1401)

**Comment by Giappo** [comment]
Sorry Richel. My bad.
I'll fix it soon!

**Comment by richelbilderbeek** [comment]
No worries, there's no rush :+1:

**Comment by Giappo** [comment]
Ok, try again.
Furthermore, check if the package is called with the more recent name ("mbd.SimTree" instead of "mbd.TaxaAndMbness")

**Comment by richelbilderbeek** [comment]
Another attempt with [this commit](https://github.com/richelbilderbeek/razzo/commit/077522717a8be038514d69136dfc36f9cabcb0ae)... :rainbow:

**Comment by Giappo** [comment]
Dependency on Razzo has been removed. Is it still not working? @richelbilderbeek

**Comment by richelbilderbeek** [comment]
Works! Well done :+1:
